"""Apply the approved editorial wording after importing the research document."""
from pathlib import Path
import re
site=Path(__file__).resolve().parents[1]
p=site/'index.html';s=p.read_text()
def paragraph(needle,replacement):
 global s
 s=re.sub(r'<p([^>]*)>(.*?)</p>',lambda m:'<p'+m[1]+'>'+replacement+'</p>' if needle in m[2] else m[0],s,flags=re.S)
paragraph('The polybaric melting was calculated','Polybaric melting is calculated using the standard residual mantle column (RMC) model of Langmuir, Klein, and Plank (1992). The melt composition (C<sub>L</sub>) for each element is calculated using the mass balance relationships in Eq. m1:')
paragraph('was calculated as the extent of melting reflected','Here C<sub>0</sub> is the source composition, C<sub>S</sub> is the residual solid composition, F is the extent of melting, and D is the bulk partition coefficient. In the RMC model, F represents the pooled melt fraction of the melting column. The calculation first determines the instantaneous melt fraction (F<sub>inst</sub>) generated by each pressure decrement (Eq. m2a), then the accumulated melt fraction (F<sub>accu</sub>) at a given pressure (Eq. m2b), and finally the pooled melt fraction relative to the system at that pressure (Eq. m2c):')
paragraph('are from previous step','Here F<sub>accu</sub> and P are the values from the previous step, with P expressed in kbar. The derivation of these equations is described in Langmuir, Klein, and Plank (1992).')
paragraph('equals to the current decrement step','Here n is the index of the current pressure-decrement step, and N is the total number of steps through the current step.')
# Preserve the newly supplied partition-coefficient notation.
s=s.replace('The bulk partitioning coefficients (','The bulk partition coefficients (').replace('for each element were calculated based on the partitioning coefficients for each mantle silicate phases','for each element are calculated from the partition coefficients of the mantle silicate phases').replace('during the melting (Eq. m3-m4).','during melting (Eqs. m3–m4).')
s=s.replace('at the previous step, and','at the previous step, and').replace('is the coefficient for the mineral phase in melting reactions. The melt compositions for polybaric melting then can be calculated by combining the Equations m1-m4.','is its coefficient in the melting reaction. The melt compositions along the polybaric melting path are then calculated by combining Eqs. m1–m4.')
s=s.replace('The model can simulate both fractional and equilibrium melting with both polybaric and isobaric settings.','The model can simulate fractional and equilibrium melting under both polybaric and isobaric conditions.')
s=s.replace('mass balance equations applied in melting calculation','mass balance equations used in the melting calculation')
paragraph('The melt and mineral compositions were also calculated','Melt and mineral compositions are also calculated using mass balance (Eq. m1). Here C<sub>0</sub> is the primitive magma composition, C<sub>L</sub> is the remaining melt composition, and C<sub>S</sub> is the composition of the crystallized solid, which may contain several minerals. The remaining melt fraction, F, depends on the crystallized mineral fractions, F<sub>a</sub> (Eq. c1). The crystallization degree is 1 − F.')
s=s.replace('The main problem is finding the correct proportions of minerals being crystallized. The correct mineral proportions are those that conserve the bulk composition and leave the melt saturated with every mineral present.','The calculation seeks mineral proportions that conserve the bulk composition and leave the melt saturated with every mineral present.')
s=s.replace('The Newton–Raphson method adjusts the mineral fractions together by solving</p>','The Newton–Raphson method adjusts the mineral fractions together by solving:</p>')
s=s.replace('and the target is zero,  ','with a target value of zero; ').replace('At equilibrium, every mineral present has','At equilibrium, every mineral present satisfies').replace(' = 0, all phase fractions are nonnegative and sum to one, including the remaining melt. With the melt and mineral proportions being calculated, their compositions can be calculated based on the mass balance.',' = 0. All phase fractions, including the remaining melt, are nonnegative and sum to one. Once the melt and mineral proportions are known, their compositions are calculated from mass balance.')
s=s.replace('Example setting: Source composition: depleted mantle composition','Example settings: source composition: depleted mantle').replace('; Rock mode:', '; initial mineral proportions:').replace('; Melting reactions: from Walter (1998); Starting pressure:', '; melting reactions: Walter (1998); starting pressure:')
s=s.replace('Example setting: Source composition: synthetic parental basaltic magma compositions; Crystallization pressure:','Example settings: source composition: synthetic parental basaltic magma; crystallization pressure:')
s=s.replace('The spinel phase was created from a garnet-to-spinel conversion reaction.','Spinel forms through a garnet-to-spinel conversion reaction.')
s=s.replace('The model is compared with the 3 GPa isobaric equilibrium melting experiment by Walter (1998). The model applied the same source compositions, rock mode, and melting reactions as the experiment.','Model results are compared with the 3 GPa isobaric equilibrium melting experiments of Walter (1998). The calculations use the same source compositions, initial mineral proportions, and melting reactions as the experiments.')
s=s.replace('is MgO partitioning coefficient','is the MgO partition coefficient').replace('is temperature in Kelvin','is temperature in kelvin').replace('is SiO2 concentration in the liquid.','is the SiO<sub>2</sub> concentration in the liquid.')
paragraph('When comparing the experimental values','Compared with experimental values, the new Ni partitioning equation has a smaller relative root mean square error (RRMSE), a higher R<sup>2</sup>, a smaller intercept, and a slope closer to one than the widely used parameterizations of Beattie (1993) and Matzen et al. (2017).')
paragraph('The details of the experimental dataset','Details of the experimental dataset and comparisons are provided in Yu &amp; Langmuir (2023).')
paragraph('I combine geochemistry, numerical modeling','I am a PhD-trained quantitative geoscientist and Harvard postdoctoral researcher. My work combines geochemistry, scientific modeling, data analysis, and machine-learning techniques, when applicable, to investigate Earth processes and solve real-world problems.')
s=s.replace('<h2>Mingzhen Yu</h2>','').replace('Contact Mingzhen <span aria-hidden="true">↗</span>','Contact Mingzhen')
# Finish the variable-definition sentences without altering the equations.
s=s.replace('<p>where ', '<p>Here ')
s=s.replace('liquid,  ', 'liquid; ').replace('temperature in kelvin, ', 'temperature in kelvin; and ')
s=re.sub(r'(<p[^>]*>Here .*?current saturation residual.*?)</math>,  <math',r'\1</math>; and <math',s,flags=re.S)
# Keep the typography-review edits when rebuilding from the source document.
s=s.replace('I implemented mantle melting calculations', 'I implemented mantle melting modeling').replace('and source compositions. Together', 'and source compositions for mantle activity. Together')
if 'These melting and crystallization simulations' not in s:
 s=s.replace('      <div class="intro-resources">', '      <p class="hero-contribution">These melting and crystallization simulations support both forward and inverse modeling, depending on the research objective.</p>\n      <div class="intro-resources">')
s=s.replace('<p>if <math', '<p class="equation-condition">if <math').replace('<p>The bulk partition coefficients', '<p class="partition-intro">The bulk partition coefficients')
s=s.replace('parameterizations of Beattie (1993) and Matzen et al. (2017).', 'parameterizations of <a href="https://link.springer.com/article/10.1007/bf00712982">Beattie (1993)</a> and <a href="https://link.springer.com/article/10.1007/s00410-016-1319-8">Matzen et al. (2017)</a>.')
s=s.replace('<p class="eyebrow">About the researcher</p>', '<h2>About the Researcher</h2>')
s=s.replace('Research content by Mingzhen Yu; website developed with assistance from OpenAI Codex.', 'Website content by Mingzhen Yu; layout and formatting refined with assistance from OpenAI Codex.')
s=s.replace('<a href="#top">Back to top ↑</a></footer>', '<div class="footer-end"><a href="#top">Back to top ↑</a><small>© 2026 Mingzhen Yu</small></div></footer>')
s=s.replace('and P are the values from the previous step', 'and pressure (P) are the values from the previous step')
s=s.replace('until both conditions are met.</p>', 'until both conditions are met. The model can simulate both fractional and equilibrium crystallization.</p>')
if 'class="natural-data-source"' not in s:
 s=s.replace('alt="Natural basalt olivine and modeled olivine Fo and nickel" loading="lazy"></figure></div></div>', 'alt="Natural basalt olivine and modeled olivine Fo and nickel" loading="lazy"></figure></div><p class="natural-data-source">The natural data are from <a href="https://www.nature.com/articles/nature03411">Sobolev et al. (2005)</a>.</p></div>')
s=s.replace('from Salters &amp; Stracke (2004)', 'from <a href="https://agupubs.onlinelibrary.wiley.com/doi/abs/10.1029/2003GC000597">Salters &amp; Stracke (2004)</a>')
for prefix in ('melting reactions: ', 'experiments of '):
 s=s.replace(prefix+'Walter (1998)', prefix+'<a href="https://academic.oup.com/petrology/article-abstract/39/1/29/1546015">Walter (1998)</a>')
intro_references={
 'Langmuir, Klein, and Plank (1992)': 'https://doi.org/10.1029/GM071p0183',
 'Weaver and Langmuir (1990)': 'https://doi.org/10.1016/0098-3004(90)90074-4',
}
def link_intro(match):
 text=match[0]
 for label,url in intro_references.items():
  if f'href="{url}"' not in text:
   text=text.replace(label,f'<a href="{url}">{label}</a>')
 return text
s=re.sub(r'<p class="intro">.*?</p>',link_intro,s,flags=re.S)
p.write_text(s)
